default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: saruni
  password: saruni23
  database: egypt
  port: 5432

development:
  <<: *default
  database: egypt

test:
  <<: *default
  database: egypt

production:
  <<: *default
  database: egypt